server.port: 38083

spring:
  application:
    name: sms-service
  config:
    import: classpath:flyway.yml
  data:
    redis:
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/apzda_infra_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Abc12332!
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

apzda:
  cloud:
    sms:
      providers:
        - id: test
          name: 测试的供应商
          templates:
            login:
              template-id: "1234"
              name: 登录验证码
      props:
        thread: 2
      templates:
        login:
          interval: 60s
          timeout: 15m

logging:
  level:
    com.apzda: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %msg%n"


